// Catálogo estático de insumos e materiais de engenharia (referência SINAPI/mercado BR).
// Cada item: [descricao, unidade padrão]. Usado no autopreenchimento da solicitação de compra.
// Catálogo local (sem backend): busca é feita no cliente, sem custo de rede.

const CATALOGO = [
    ['Aglomerantes e agregados', [
        ['Cimento CP-II-E-32 saco 50 kg', 'sc'],
        ['Cimento CP-II-F-32 saco 50 kg', 'sc'],
        ['Cimento CP-III-40 saco 50 kg', 'sc'],
        ['Cimento CP-V ARI saco 50 kg', 'sc'],
        ['Cimento branco estrutural saco 25 kg', 'sc'],
        ['Cal hidratada CH-I saco 20 kg', 'sc'],
        ['Cal hidratada CH-III saco 20 kg', 'sc'],
        ['Cal virgem saco 20 kg', 'sc'],
        ['Areia fina lavada', 'm³'],
        ['Areia média lavada', 'm³'],
        ['Areia grossa lavada', 'm³'],
        ['Areia de aterro', 'm³'],
        ['Pedra brita nº 0 (pedrisco)', 'm³'],
        ['Pedra brita nº 1', 'm³'],
        ['Pedra brita nº 2', 'm³'],
        ['Pedra brita nº 3', 'm³'],
        ['Pedra rachão', 'm³'],
        ['Bica corrida / brita graduada', 'm³'],
        ['Pó de pedra', 'm³'],
        ['Seixo rolado', 'm³'],
        ['Argila expandida saco 50 L', 'sc'],
        ['Terra vegetal / adubada', 'm³'],
    ]],
    ['Concreto e argamassas', [
        ['Concreto usinado bombeável fck 20 MPa', 'm³'],
        ['Concreto usinado bombeável fck 25 MPa', 'm³'],
        ['Concreto usinado bombeável fck 30 MPa', 'm³'],
        ['Concreto usinado bombeável fck 35 MPa', 'm³'],
        ['Concreto usinado convencional fck 25 MPa', 'm³'],
        ['Bombeamento de concreto', 'm³'],
        ['Argamassa colante AC-I saco 20 kg', 'sc'],
        ['Argamassa colante AC-II saco 20 kg', 'sc'],
        ['Argamassa colante AC-III saco 20 kg', 'sc'],
        ['Argamassa colante para porcelanato saco 20 kg', 'sc'],
        ['Argamassa de assentamento pronta saco 50 kg', 'sc'],
        ['Argamassa de reboco pronta saco 50 kg', 'sc'],
        ['Argamassa autonivelante saco 25 kg', 'sc'],
        ['Graute saco 25 kg', 'sc'],
        ['Rejunte flexível saco 1 kg', 'kg'],
        ['Rejunte epóxi caixa 1 kg', 'kg'],
        ['Aditivo plastificante para argamassa 18 L', 'gl'],
        ['Aditivo impermeabilizante para concreto 18 L', 'balde'],
        ['Aditivo acelerador de pega 5 L', 'gl'],
        ['Desmoldante para fôrmas 18 L', 'balde'],
    ]],
    ['Alvenaria — blocos e tijolos', [
        ['Tijolo cerâmico furado 9x19x19 cm', 'mil'],
        ['Tijolo cerâmico furado 11,5x19x19 cm', 'mil'],
        ['Tijolo cerâmico furado 14x19x29 cm', 'mil'],
        ['Tijolo maciço comum 5x10x20 cm', 'mil'],
        ['Tijolo aparente 5,5x11x23 cm', 'mil'],
        ['Bloco de concreto estrutural 14x19x39 cm', 'un'],
        ['Bloco de concreto estrutural 19x19x39 cm', 'un'],
        ['Bloco de concreto vedação 9x19x39 cm', 'un'],
        ['Bloco de concreto vedação 14x19x39 cm', 'un'],
        ['Canaleta de concreto 14x19x39 cm', 'un'],
        ['Canaleta de concreto 19x19x39 cm', 'un'],
        ['Bloco de concreto celular autoclavado 10x30x60 cm', 'un'],
        ['Bloco de concreto celular autoclavado 12,5x30x60 cm', 'un'],
        ['Bloco de vidro 19x19x8 cm', 'un'],
        ['Cobogó de concreto 9x39x39 cm', 'un'],
        ['Elemento vazado cerâmico 20x20 cm', 'un'],
        ['Vergas e contravergas pré-moldadas', 'm'],
        ['Meio-fio / guia de concreto', 'm'],
        ['Piso intertravado de concreto 10x20x6 cm', 'm²'],
        ['Piso grama de concreto', 'm²'],
    ]],
    ['Aço e ferragens estruturais', [
        ['Vergalhão CA-50 6,3 mm barra 12 m', 'br'],
        ['Vergalhão CA-50 8,0 mm barra 12 m', 'br'],
        ['Vergalhão CA-50 10,0 mm barra 12 m', 'br'],
        ['Vergalhão CA-50 12,5 mm barra 12 m', 'br'],
        ['Vergalhão CA-50 16,0 mm barra 12 m', 'br'],
        ['Vergalhão CA-50 20,0 mm barra 12 m', 'br'],
        ['Vergalhão CA-50 25,0 mm barra 12 m', 'br'],
        ['Vergalhão CA-60 4,2 mm barra 12 m', 'br'],
        ['Vergalhão CA-60 5,0 mm barra 12 m', 'br'],
        ['Aço cortado e dobrado CA-50', 'kg'],
        ['Tela soldada Q-92 2,45x6,00 m', 'pç'],
        ['Tela soldada Q-138 2,45x6,00 m', 'pç'],
        ['Tela soldada Q-196 2,45x6,00 m', 'pç'],
        ['Treliça nervurada TG8 barra 12 m', 'br'],
        ['Treliça nervurada TG12 barra 12 m', 'br'],
        ['Coluna pronta 7x14 cm 4 ferros 3/8"', 'un'],
        ['Estribo pronto 7x17 cm', 'un'],
        ['Arame recozido nº 18', 'kg'],
        ['Arame galvanizado nº 12', 'kg'],
        ['Espaçador plástico para armadura', 'cto'],
        ['Perfil metálico I / W (estrutura metálica)', 'kg'],
        ['Perfil U enrijecido (steel frame / terça)', 'br'],
        ['Cantoneira de aço', 'br'],
        ['Chapa de aço xadrez', 'm²'],
        ['Prego 17x27 com cabeça', 'kg'],
        ['Prego 18x30 com cabeça', 'kg'],
        ['Prego 15x15 com cabeça', 'kg'],
        ['Prego telheiro 18x30', 'kg'],
    ]],
    ['Madeiras e fôrmas', [
        ['Tábua de pinho 1"x12" (2,5x30 cm) 3 m', 'un'],
        ['Tábua de pinho 1"x8" (2,5x20 cm) 3 m', 'un'],
        ['Sarrafo de pinho 1"x3" (2,5x7,5 cm) 3 m', 'un'],
        ['Ripa de pinho 1x5 cm 3 m', 'un'],
        ['Pontalete de pinho 3"x3" (7,5x7,5 cm) 3 m', 'un'],
        ['Viga de madeira 6x12 cm', 'm'],
        ['Viga de madeira 6x16 cm', 'm'],
        ['Caibro de madeira 5x6 cm', 'm'],
        ['Ripa de madeira para telhado 1,5x5 cm', 'm'],
        ['Chapa de compensado resinado 12 mm 1,10x2,20 m', 'un'],
        ['Chapa de compensado resinado 17 mm 1,10x2,20 m', 'un'],
        ['Chapa de compensado plastificado 18 mm 1,10x2,20 m', 'un'],
        ['Chapa OSB 11,1 mm 1,20x2,40 m', 'un'],
        ['Escora metálica telescópica 3 m (locação)', 'un'],
        ['Escora de eucalipto 3 m', 'un'],
        ['Andaime metálico 1,0x1,5 m (locação mensal)', 'un'],
        ['Plataforma / painel metálico para andaime', 'un'],
        ['Deck de madeira tratada', 'm²'],
    ]],
    ['Cobertura e telhas', [
        ['Telha cerâmica portuguesa', 'mil'],
        ['Telha cerâmica romana', 'mil'],
        ['Telha cerâmica colonial', 'mil'],
        ['Telha cerâmica americana', 'mil'],
        ['Telha de fibrocimento ondulada 6 mm 2,44x1,10 m', 'un'],
        ['Telha de fibrocimento ondulada 6 mm 1,83x1,10 m', 'un'],
        ['Telha metálica trapezoidal TP40 0,43 mm', 'm²'],
        ['Telha metálica ondulada 0,43 mm', 'm²'],
        ['Telha sanduíche (termoacústica) EPS 30 mm', 'm²'],
        ['Telha sanduíche (termoacústica) PIR 30 mm', 'm²'],
        ['Telha translúcida de policarbonato ondulada', 'un'],
        ['Telha ecológica ondulada 2,00x0,95 m', 'un'],
        ['Cumeeira cerâmica', 'un'],
        ['Cumeeira de fibrocimento', 'un'],
        ['Cumeeira metálica', 'm'],
        ['Rufo de chapa galvanizada corte 25 cm', 'm'],
        ['Rufo de chapa galvanizada corte 33 cm', 'm'],
        ['Calha de chapa galvanizada corte 33 cm', 'm'],
        ['Calha de chapa galvanizada corte 50 cm', 'm'],
        ['Condutor pluvial PVC quadrado 88x88 mm', 'm'],
        ['Manta térmica subcobertura 2 faces', 'rl'],
        ['Parafuso telheiro com vedação', 'cto'],
        ['Gancho / suporte para calha', 'un'],
        ['Domus / claraboia', 'un'],
    ]],
    ['Impermeabilização e químicos', [
        ['Manta asfáltica 3 mm rolo 10 m²', 'rl'],
        ['Manta asfáltica 4 mm rolo 10 m²', 'rl'],
        ['Manta asfáltica aluminizada 3 mm rolo 10 m²', 'rl'],
        ['Manta líquida acrílica balde 18 kg', 'balde'],
        ['Impermeabilizante flexível bicomponente 18 kg', 'balde'],
        ['Argamassa polimérica impermeabilizante 18 kg', 'balde'],
        ['Emulsão asfáltica impermeabilizante 18 L', 'balde'],
        ['Primer asfáltico 18 L', 'balde'],
        ['Impermeabilizante para concreto (aditivo) 18 L', 'balde'],
        ['Hidrofugante de silicone incolor 5 L', 'gl'],
        ['Vedação flexível PU (tipo Sikaflex) 300 mL', 'tb'],
        ['Silicone neutro incolor 280 g', 'tb'],
        ['Espuma expansiva de poliuretano 500 mL', 'tb'],
        ['Fita autoadesiva asfáltica multiuso 10 cm x 10 m', 'rl'],
        ['Junta de dilatação / mastique', 'm'],
        ['Geotêxtil (bidim) RT-9', 'm²'],
        ['Lona plástica preta 4x100 m 150 micra', 'rl'],
        ['Filme de polietileno para laje', 'm²'],
        ['Removedor / limpa pedras 5 L', 'gl'],
        ['Resina acrílica para pedras 18 L', 'balde'],
    ]],
    ['Hidráulica — água fria e quente', [
        ['Tubo PVC soldável 20 mm barra 6 m', 'br'],
        ['Tubo PVC soldável 25 mm barra 6 m', 'br'],
        ['Tubo PVC soldável 32 mm barra 6 m', 'br'],
        ['Tubo PVC soldável 50 mm barra 6 m', 'br'],
        ['Tubo PVC soldável 60 mm barra 6 m', 'br'],
        ['Tubo CPVC 22 mm barra 3 m', 'br'],
        ['Tubo CPVC 28 mm barra 3 m', 'br'],
        ['Tubo PEX 16 mm rolo 50 m', 'rl'],
        ['Tubo PPR 25 mm barra 3 m', 'br'],
        ['Joelho 90° soldável 25 mm', 'un'],
        ['Joelho 90° soldável 32 mm', 'un'],
        ['Joelho 90° soldável com rosca (azul) 25 mm x 1/2"', 'un'],
        ['Tê soldável 25 mm', 'un'],
        ['Tê soldável 32 mm', 'un'],
        ['Luva soldável 25 mm', 'un'],
        ['Luva soldável com rosca 25 mm x 3/4"', 'un'],
        ['Curva 90° soldável 25 mm', 'un'],
        ['Adaptador soldável curto 25 mm x 3/4"', 'un'],
        ['Registro de esfera soldável 25 mm', 'un'],
        ['Registro de esfera soldável 32 mm', 'un'],
        ['Registro de gaveta bruto 3/4"', 'un'],
        ['Registro de gaveta com canopla cromada 3/4"', 'un'],
        ['Registro de pressão com canopla cromada 3/4"', 'un'],
        ['Válvula de retenção 3/4"', 'un'],
        ['Adesivo plástico para PVC 175 g', 'un'],
        ['Adesivo plástico para PVC 850 g', 'un'],
        ['Solução limpadora para PVC 1 L', 'un'],
        ['Fita veda-rosca 18 mm x 50 m', 'rl'],
        ['Caixa d’água polietileno 500 L', 'un'],
        ['Caixa d’água polietileno 1.000 L', 'un'],
        ['Caixa d’água polietileno 2.000 L', 'un'],
        ['Boia / torneira de boia para caixa d’água 3/4"', 'un'],
        ['Flange para caixa d’água 25 mm', 'un'],
        ['Barrilete / kit instalação de caixa d’água', 'jg'],
        ['Pressurizador de água', 'un'],
        ['Aquecedor de água a gás 15 L/min', 'un'],
        ['Hidrômetro 3/4"', 'un'],
    ]],
    ['Hidráulica — esgoto e pluvial', [
        ['Tubo PVC esgoto 40 mm barra 6 m', 'br'],
        ['Tubo PVC esgoto 50 mm barra 6 m', 'br'],
        ['Tubo PVC esgoto 75 mm barra 6 m', 'br'],
        ['Tubo PVC esgoto 100 mm barra 6 m', 'br'],
        ['Tubo PVC esgoto 150 mm barra 6 m', 'br'],
        ['Joelho 90° esgoto 40 mm', 'un'],
        ['Joelho 90° esgoto 50 mm', 'un'],
        ['Joelho 90° esgoto 100 mm', 'un'],
        ['Joelho 45° esgoto 100 mm', 'un'],
        ['Tê esgoto 100x100 mm', 'un'],
        ['Junção simples esgoto 100x100 mm', 'un'],
        ['Luva esgoto 100 mm', 'un'],
        ['Redução esgoto 100x75 mm', 'un'],
        ['Curva 90° longa esgoto 100 mm', 'un'],
        ['Caixa sifonada 150x150x50 mm', 'un'],
        ['Caixa sifonada 250x230x75 mm', 'un'],
        ['Ralo seco 100x100x40 mm', 'un'],
        ['Ralo linear 90 cm', 'un'],
        ['Grelha inox 15x15 cm', 'un'],
        ['Caixa de gordura PVC 250x230x75 mm', 'un'],
        ['Caixa de inspeção PVC 300 mm', 'un'],
        ['Caixa de passagem alvenaria 60x60 cm (tampa)', 'un'],
        ['Fossa séptica polietileno 1.100 L', 'un'],
        ['Filtro anaeróbio 1.000 L', 'un'],
        ['Sumidouro — anel de concreto 1,0 m', 'un'],
        ['Tubo corrugado dreno 100 mm', 'm'],
        ['Anel de vedação para vaso sanitário', 'un'],
        ['Tubo de queda / ligação do vaso 100 mm', 'un'],
    ]],
    ['Louças e metais sanitários', [
        ['Vaso sanitário com caixa acoplada branco', 'un'],
        ['Vaso sanitário convencional branco', 'un'],
        ['Caixa de descarga embutida com placa', 'un'],
        ['Assento sanitário soft close', 'un'],
        ['Lavatório com coluna branco', 'un'],
        ['Cuba de embutir oval louça branca', 'un'],
        ['Cuba de apoio louça branca', 'un'],
        ['Cuba de inox para cozinha 56x34 cm', 'un'],
        ['Tanque de louça 22 L com coluna', 'un'],
        ['Tanque de mármore sintético 1 m', 'un'],
        ['Torneira para lavatório de mesa cromada', 'un'],
        ['Torneira para cozinha de parede cromada', 'un'],
        ['Torneira de jardim 3/4" metal', 'un'],
        ['Misturador monocomando para lavatório', 'un'],
        ['Misturador monocomando para cozinha', 'un'],
        ['Chuveiro elétrico 220 V 7.500 W', 'un'],
        ['Ducha / chuveiro de metal para água quente', 'un'],
        ['Ducha higiênica cromada', 'un'],
        ['Sifão sanfonado universal', 'un'],
        ['Sifão de metal cromado 1"', 'un'],
        ['Válvula para lavatório cromada', 'un'],
        ['Engate flexível 40 cm', 'un'],
        ['Barra de apoio inox 80 cm (PNE)', 'un'],
        ['Papeleira / acessórios de banheiro (kit 5 pçs)', 'jg'],
    ]],
    ['Elétrica — cabos e infraestrutura', [
        ['Cabo flexível 1,5 mm² 750 V rolo 100 m', 'rl'],
        ['Cabo flexível 2,5 mm² 750 V rolo 100 m', 'rl'],
        ['Cabo flexível 4,0 mm² 750 V rolo 100 m', 'rl'],
        ['Cabo flexível 6,0 mm² 750 V rolo 100 m', 'rl'],
        ['Cabo flexível 10 mm² 750 V', 'm'],
        ['Cabo flexível 16 mm² 750 V', 'm'],
        ['Cabo PP 3x2,5 mm²', 'm'],
        ['Cabo concêntrico 2x10 mm² (entrada)', 'm'],
        ['Cabo de cobre nu 16 mm² (aterramento)', 'm'],
        ['Eletroduto corrugado 20 mm rolo 50 m', 'rl'],
        ['Eletroduto corrugado 25 mm rolo 50 m', 'rl'],
        ['Eletroduto corrugado 32 mm rolo 25 m', 'rl'],
        ['Eletroduto corrugado reforçado (laje) 25 mm rolo 50 m', 'rl'],
        ['Eletroduto PVC rígido 3/4" barra 3 m', 'br'],
        ['Eletroduto PVC rígido 1" barra 3 m', 'br'],
        ['Curva 90° para eletroduto rígido 3/4"', 'un'],
        ['Caixa de luz 4x2 amarela', 'un'],
        ['Caixa de luz 4x4 amarela', 'un'],
        ['Caixa octogonal 4x4 com fundo móvel', 'un'],
        ['Caixa de passagem sobrepor 100x100 mm', 'un'],
        ['Quadro de distribuição embutir 12/16 disjuntores', 'un'],
        ['Quadro de distribuição embutir 24/32 disjuntores', 'un'],
        ['Haste de aterramento 5/8" x 2,40 m', 'un'],
        ['Conector para haste de aterramento', 'un'],
        ['Padrão de entrada monofásico completo', 'vb'],
        ['Padrão de entrada trifásico completo', 'vb'],
        ['Poste de concreto duplo T 7,5 m', 'un'],
        ['Abraçadeira / fita hellermann (pacote 100)', 'pct'],
        ['Fita isolante 19 mm x 20 m', 'rl'],
        ['Fita isolante autofusão 19 mm x 10 m', 'rl'],
        ['Conector de torção (pacote 100)', 'pct'],
        ['Terminal tubular / ilhós 2,5 mm² (pacote 100)', 'pct'],
        ['Canaleta PVC 20x10 mm barra 2 m', 'br'],
        ['Cabo de rede UTP Cat.6 caixa 305 m', 'cx'],
        ['Cabo coaxial RG6 rolo 100 m', 'rl'],
    ]],
    ['Elétrica — dispositivos e proteção', [
        ['Disjuntor monopolar DIN 10 A curva C', 'un'],
        ['Disjuntor monopolar DIN 16 A curva C', 'un'],
        ['Disjuntor monopolar DIN 20 A curva C', 'un'],
        ['Disjuntor monopolar DIN 25 A curva C', 'un'],
        ['Disjuntor monopolar DIN 32 A curva C', 'un'],
        ['Disjuntor monopolar DIN 40 A curva C', 'un'],
        ['Disjuntor bipolar DIN 25 A curva C', 'un'],
        ['Disjuntor bipolar DIN 32 A curva C', 'un'],
        ['Disjuntor bipolar DIN 40 A curva C', 'un'],
        ['Disjuntor tripolar DIN 40 A curva C', 'un'],
        ['Disjuntor tripolar DIN 63 A curva C', 'un'],
        ['Interruptor DR bipolar 40 A 30 mA', 'un'],
        ['Interruptor DR tetrapolar 40 A 30 mA', 'un'],
        ['DPS 275 V 20 kA classe II', 'un'],
        ['Interruptor simples 1 tecla com placa 4x2', 'un'],
        ['Interruptor simples 2 teclas com placa 4x2', 'un'],
        ['Interruptor paralelo (three-way) com placa', 'un'],
        ['Interruptor intermediário (four-way) com placa', 'un'],
        ['Tomada 2P+T 10 A com placa 4x2', 'un'],
        ['Tomada 2P+T 20 A com placa 4x2', 'un'],
        ['Conjunto interruptor + tomada 10 A com placa', 'un'],
        ['Tomada de sobrepor externa 10 A', 'un'],
        ['Campainha residencial sem fio', 'un'],
        ['Sensor de presença para iluminação', 'un'],
        ['Fotocélula para iluminação externa', 'un'],
        ['Contactor tripolar 25 A', 'un'],
        ['Timer / temporizador digital DIN', 'un'],
        ['Extensão elétrica 10 m 2P+T', 'un'],
    ]],
    ['Iluminação', [
        ['Lâmpada LED bulbo 9 W E27 6500 K', 'un'],
        ['Lâmpada LED bulbo 12 W E27 6500 K', 'un'],
        ['Lâmpada LED bulbo alta potência 30 W E27', 'un'],
        ['Painel LED de embutir quadrado 18 W', 'un'],
        ['Painel LED de embutir redondo 24 W', 'un'],
        ['Painel LED de sobrepor 24 W', 'un'],
        ['Luminária tubular LED 18 W 120 cm completa', 'un'],
        ['Spot de embutir dicroica GU10 com lâmpada', 'un'],
        ['Fita LED 12 V rolo 5 m com fonte', 'rl'],
        ['Perfil de alumínio para fita LED 2 m', 'br'],
        ['Refletor LED 50 W bivolt', 'un'],
        ['Refletor LED 100 W bivolt', 'un'],
        ['Refletor LED 200 W bivolt', 'un'],
        ['Arandela externa alumínio', 'un'],
        ['Balizador de embutir para escada', 'un'],
        ['Poste de jardim 1 luminária', 'un'],
        ['Luminária de emergência LED', 'un'],
        ['Soquete E27 com rabicho', 'un'],
        ['Plafon de sobrepor com lâmpada', 'un'],
    ]],
    ['Pintura', [
        ['Tinta acrílica fosca standard branca 18 L', 'lt'],
        ['Tinta acrílica fosca premium branca 18 L', 'lt'],
        ['Tinta acrílica acetinada premium branca 18 L', 'lt'],
        ['Tinta acrílica fosca cor pronta 18 L', 'lt'],
        ['Tinta acrílica 3,6 L', 'gl'],
        ['Tinta esmalte sintético brilhante 3,6 L', 'gl'],
        ['Tinta esmalte à base d’água 3,6 L', 'gl'],
        ['Tinta epóxi para piso 3,6 L', 'gl'],
        ['Tinta para piso acrílica 18 L', 'lt'],
        ['Verniz marítimo 3,6 L', 'gl'],
        ['Stain impregnante para madeira 3,6 L', 'gl'],
        ['Zarcão / fundo antiferrugem 3,6 L', 'gl'],
        ['Massa corrida PVA barrica 25 kg', 'barrica'],
        ['Massa acrílica barrica 25 kg', 'barrica'],
        ['Selador acrílico 18 L', 'lt'],
        ['Fundo preparador de paredes 18 L', 'lt'],
        ['Textura acrílica rústica 25 kg', 'barrica'],
        ['Grafiato / textura riscada 25 kg', 'barrica'],
        ['Cal para pintura (caiação) saco 8 kg', 'sc'],
        ['Solvente / aguarrás 5 L', 'gl'],
        ['Thinner 5 L', 'gl'],
        ['Corante líquido para tinta 50 mL', 'un'],
        ['Lixa para massa/parede grão 120', 'un'],
        ['Lixa para massa/parede grão 220', 'un'],
        ['Lixa d’água grão 150', 'un'],
        ['Lixa para ferro grão 80', 'un'],
        ['Rolo de lã de carneiro 23 cm com suporte', 'un'],
        ['Rolo de lã antigota 23 cm (refil)', 'un'],
        ['Rolo de espuma 9 cm', 'un'],
        ['Rolo para textura/grafiato', 'un'],
        ['Trincha / pincel 2"', 'un'],
        ['Trincha / pincel 3"', 'un'],
        ['Fita crepe 24 mm x 50 m', 'rl'],
        ['Fita crepe 48 mm x 50 m', 'rl'],
        ['Lona plástica para proteção 4x25 m', 'rl'],
        ['Papelão ondulado para proteção de piso', 'rl'],
        ['Desempenadeira de aço para massa', 'un'],
        ['Espátula de aço 10 cm', 'un'],
        ['Bandeja para pintura 23 cm', 'un'],
        ['Prolongador / cabo de alumínio 3 m', 'un'],
    ]],
    ['Revestimentos e pisos', [
        ['Porcelanato acetinado 60x60 cm', 'm²'],
        ['Porcelanato polido 80x80 cm', 'm²'],
        ['Porcelanato 60x120 cm', 'm²'],
        ['Porcelanato externo antiderrapante 60x60 cm', 'm²'],
        ['Piso cerâmico PEI-4 45x45 cm', 'm²'],
        ['Piso cerâmico PEI-5 60x60 cm', 'm²'],
        ['Azulejo / revestimento cerâmico 30x60 cm', 'm²'],
        ['Revestimento cerâmico tipo subway 10x20 cm', 'm²'],
        ['Pastilha de porcelana placa 30x30 cm', 'm²'],
        ['Piso vinílico em régua click 4 mm', 'm²'],
        ['Piso vinílico em manta 2 mm', 'm²'],
        ['Piso laminado click 7 mm', 'm²'],
        ['Manta acústica para piso (subpiso)', 'm²'],
        ['Rodapé de poliestireno 10 cm barra 2,40 m', 'br'],
        ['Rodapé de porcelanato 10 cm', 'm'],
        ['Perfil / cordão de alumínio para piso', 'br'],
        ['Soleira de granito 15 cm', 'm'],
        ['Peitoril de granito 17 cm com pingadeira', 'm'],
        ['Bancada de granito para cozinha', 'm²'],
        ['Bancada de granito para banheiro com cuba', 'un'],
        ['Mármore / granito sob medida', 'm²'],
        ['Pedra São Tomé serrada', 'm²'],
        ['Pedra miracema', 'm²'],
        ['Espaçador nivelador de piso 1 mm (pacote 100)', 'pct'],
        ['Cunha para nivelador de piso (pacote 100)', 'pct'],
        ['Cruzeta / espaçador 2 mm (pacote 100)', 'pct'],
        ['Grama esmeralda em placas', 'm²'],
        ['Grama sintética 20 mm', 'm²'],
    ]],
    ['Gesso e drywall', [
        ['Gesso em pó para fundição saco 40 kg', 'sc'],
        ['Gesso cola saco 5 kg', 'sc'],
        ['Placa de gesso comum 60x60 cm', 'un'],
        ['Chapa de drywall ST branca 12,5 mm 1,20x1,80 m', 'un'],
        ['Chapa de drywall RU verde (resistente à umidade) 12,5 mm', 'un'],
        ['Chapa de drywall RF rosa (resistente ao fogo) 12,5 mm', 'un'],
        ['Chapa cimentícia 10 mm 1,20x2,40 m', 'un'],
        ['Perfil guia drywall 48 mm barra 3 m', 'br'],
        ['Perfil montante drywall 48 mm barra 3 m', 'br'],
        ['Perfil canaleta F530 para forro barra 3 m', 'br'],
        ['Tabica metálica para forro barra 3 m', 'br'],
        ['Regulador / suporte nivelador F530', 'un'],
        ['Arame galvanizado nº 10 para forro', 'kg'],
        ['Parafuso drywall ponta agulha 3,5x25 mm (caixa 1.000)', 'cx'],
        ['Parafuso metal-metal (caixa 1.000)', 'cx'],
        ['Fita de papel para junta drywall rolo 50 m', 'rl'],
        ['Fita telada para junta rolo 90 m', 'rl'],
        ['Massa para junta drywall balde 28 kg', 'balde'],
        ['Molde / sanca de gesso', 'm'],
        ['Forro PVC régua 20 cm x 6 m branco', 'm²'],
        ['Rodaforro / acabamento PVC barra 6 m', 'br'],
        ['Forro mineral 62,5x62,5 cm (com perfilaria)', 'm²'],
    ]],
    ['Esquadrias, portas e vidros', [
        ['Porta de madeira lisa 60x210 cm', 'un'],
        ['Porta de madeira lisa 70x210 cm', 'un'],
        ['Porta de madeira lisa 80x210 cm', 'un'],
        ['Porta de madeira semioca 80x210 cm', 'un'],
        ['Kit porta pronta de madeira 80x210 cm', 'jg'],
        ['Batente / marco de madeira 14 cm', 'jg'],
        ['Guarnição / alizar de madeira 7 cm (jogo)', 'jg'],
        ['Porta de alumínio de abrir 80x210 cm', 'un'],
        ['Porta balcão de alumínio 4 folhas 200x210 cm', 'un'],
        ['Porta de aço de enrolar (comercial)', 'm²'],
        ['Porta de correr de vidro temperado 8 mm', 'm²'],
        ['Janela de alumínio de correr 2 folhas 120x100 cm', 'un'],
        ['Janela de alumínio de correr 2 folhas 150x100 cm', 'un'],
        ['Janela de alumínio máximo-ar 60x60 cm', 'un'],
        ['Janela de PVC de correr com vidro duplo', 'm²'],
        ['Veneziana de alumínio 3 folhas 120x100 cm', 'un'],
        ['Portão de garagem basculante metálico', 'm²'],
        ['Portão de garagem deslizante metálico', 'm²'],
        ['Motor para portão deslizante 1/4 HP', 'un'],
        ['Grade de ferro / proteção metálica', 'm²'],
        ['Vidro comum incolor 4 mm', 'm²'],
        ['Vidro temperado incolor 8 mm', 'm²'],
        ['Vidro laminado 6 mm', 'm²'],
        ['Espelho 4 mm lapidado', 'm²'],
        ['Guarda-corpo de vidro com torre inox', 'm'],
        ['Rede de proteção para janelas', 'm²'],
        ['Tela mosquiteira para janela', 'm²'],
    ]],
    ['Ferragens para esquadrias', [
        ['Fechadura de embutir para porta interna', 'un'],
        ['Fechadura de embutir para porta externa', 'un'],
        ['Fechadura para banheiro (tranqueta)', 'un'],
        ['Fechadura digital eletrônica', 'un'],
        ['Fechadura tetra para porta de ferro', 'un'],
        ['Dobradiça 3"x2,5" com anéis (cartela 3)', 'jg'],
        ['Dobradiça vai-e-vem 3"', 'par'],
        ['Puxador duplo inox 40 cm', 'un'],
        ['Roldana para portão 3"', 'un'],
        ['Trilho para porta de correr 2 m com kit', 'jg'],
        ['Kit porta de correr de madeira (roldanas aparentes)', 'jg'],
        ['Cadeado 40 mm', 'un'],
        ['Ferrolho / tarjeta 3"', 'un'],
        ['Mola aérea para porta', 'un'],
        ['Batedor / amortecedor de porta', 'un'],
    ]],
    ['Fixação e consumíveis', [
        ['Parafuso chipboard 4x40 mm (caixa 500)', 'cx'],
        ['Parafuso chipboard 5x60 mm (caixa 200)', 'cx'],
        ['Parafuso sextavado com bucha 8 mm', 'un'],
        ['Bucha de nylon 6 mm (pacote 100)', 'pct'],
        ['Bucha de nylon 8 mm (pacote 100)', 'pct'],
        ['Bucha de nylon 10 mm (pacote 50)', 'pct'],
        ['Chumbador parabolt 3/8"', 'un'],
        ['Chumbador químico 300 mL', 'tb'],
        ['Pino de aço para finca-pino (caixa 100)', 'cx'],
        ['Rebite de repuxo 4,8x12 mm (pacote 100)', 'pct'],
        ['Disco de corte inox 4.1/2"', 'un'],
        ['Disco de corte diamantado 4.3/8"', 'un'],
        ['Disco diamantado para porcelanato fino', 'un'],
        ['Disco de desbaste 7"', 'un'],
        ['Broca de aço rápido 6 mm', 'un'],
        ['Broca de vídea para concreto 8 mm', 'un'],
        ['Broca de vídea para concreto 10 mm', 'un'],
        ['Broca SDS Plus 10x160 mm', 'un'],
        ['Serra copo diamantada 65 mm', 'un'],
        ['Eletrodo 6013 2,5 mm (embalagem 1 kg)', 'kg'],
        ['Arame MIG 0,8 mm rolo 5 kg', 'rl'],
        ['Cola de contato 750 g', 'un'],
        ['Cola epóxi (tipo durepoxi) 100 g', 'un'],
        ['Cola instantânea 20 g', 'un'],
        ['Veda calha 280 g', 'tb'],
        ['Estopa branca saco 1 kg', 'kg'],
        ['Pano multiuso (pacote 5)', 'pct'],
        ['Saco de ráfia para entulho 90x60 cm', 'un'],
        ['Vassoura de pelo 40 cm', 'un'],
        ['Vassourão de piaçava para obra', 'un'],
    ]],
    ['EPI e segurança do trabalho', [
        ['Capacete de segurança com jugular', 'un'],
        ['Bota de segurança com bico de PVC', 'par'],
        ['Bota de borracha cano longo', 'par'],
        ['Luva de raspa de couro', 'par'],
        ['Luva de látex / nitrílica', 'par'],
        ['Luva pigmentada de malha', 'par'],
        ['Óculos de proteção incolor', 'un'],
        ['Protetor auricular tipo plug (par)', 'par'],
        ['Abafador de ruído tipo concha', 'un'],
        ['Máscara PFF2 descartável', 'un'],
        ['Respirador semifacial com filtro', 'un'],
        ['Cinto de segurança paraquedista com talabarte', 'jg'],
        ['Trava-quedas para corda 12 mm', 'un'],
        ['Corda de segurança 12 mm', 'm'],
        ['Colete refletivo', 'un'],
        ['Uniforme de brim (calça + camisa)', 'jg'],
        ['Capa de chuva PVC com capuz', 'un'],
        ['Protetor solar FPS 50 bisnaga 120 mL', 'un'],
        ['Cone de sinalização 75 cm', 'un'],
        ['Fita zebrada 70 mm x 200 m', 'rl'],
        ['Tela tapume laranja 1,20 m rolo 50 m', 'rl'],
        ['Telha / chapa de tapume metálico 2,20 m', 'un'],
        ['Chapa de madeirite para tapume 2,20x1,10 m', 'un'],
        ['Extintor de incêndio ABC 4 kg', 'un'],
        ['Kit primeiros socorros para obra', 'jg'],
        ['Placa de sinalização de segurança', 'un'],
    ]],
    ['Ferramentas e equipamentos', [
        ['Betoneira 400 L (locação mensal)', 'un'],
        ['Betoneira 400 L', 'un'],
        ['Vibrador de imersão para concreto', 'un'],
        ['Serra circular de bancada para obra', 'un'],
        ['Serra mármore 4.3/8" 1.500 W', 'un'],
        ['Esmerilhadeira angular 4.1/2"', 'un'],
        ['Furadeira de impacto 1/2" 750 W', 'un'],
        ['Martelete rompedor SDS Plus 800 W', 'un'],
        ['Parafusadeira a bateria 12 V com kit', 'un'],
        ['Máquina de solda inversora 140 A', 'un'],
        ['Compactador de solo (sapo) — locação diária', 'diária'],
        ['Placa vibratória — locação diária', 'diária'],
        ['Gerador a gasolina 3 kVA — locação diária', 'diária'],
        ['Lavadora de alta pressão', 'un'],
        ['Bomba submersa para drenagem 1/2 CV', 'un'],
        ['Carrinho de mão pneu maciço 60 L', 'un'],
        ['Gerica / carrinho de concreto 90 L', 'un'],
        ['Pá de bico com cabo', 'un'],
        ['Enxada com cabo', 'un'],
        ['Picareta com cabo', 'un'],
        ['Cavadeira articulada', 'un'],
        ['Colher de pedreiro 8"', 'un'],
        ['Desempenadeira de PVC dentada', 'un'],
        ['Régua de alumínio 2 m', 'un'],
        ['Nível de alumínio 60 cm', 'un'],
        ['Nível a laser autonivelante', 'un'],
        ['Trena de aço 8 m', 'un'],
        ['Trena a laser 40 m', 'un'],
        ['Prumo de centro 500 g', 'un'],
        ['Linha de nylon para pedreiro rolo 100 m', 'rl'],
        ['Esquadro de aço 12"', 'un'],
        ['Serrote 22"', 'un'],
        ['Arco de serra com lâmina', 'un'],
        ['Marreta 1 kg com cabo', 'un'],
        ['Martelo unha 27 mm', 'un'],
        ['Talhadeira / ponteiro 10"', 'un'],
        ['Alicate universal 8"', 'un'],
        ['Alicate amperímetro digital', 'un'],
        ['Jogo de chaves de fenda e philips', 'jg'],
        ['Escada de alumínio 7 degraus', 'un'],
        ['Escada extensível de alumínio 6 m', 'un'],
        ['Mangueira de nível 3/8" rolo 20 m', 'rl'],
        ['Mangueira de jardim 1/2" 30 m', 'un'],
        ['Cavalete metálico para obra', 'un'],
    ]],
    ['Canteiro e serviços', [
        ['Caçamba de entulho 5 m³ (remoção)', 'un'],
        ['Locação de container almoxarifado 6 m', 'mês'],
        ['Locação de banheiro químico', 'mês'],
        ['Água potável — caminhão pipa 10.000 L', 'un'],
        ['Barraco de obra / almoxarifado em madeirite', 'vb'],
        ['Ligação provisória de energia', 'vb'],
        ['Ligação provisória de água', 'vb'],
        ['Placa de obra em lona com estrutura', 'un'],
        ['Frete / transporte de material', 'vb'],
        ['Munck para descarga de material', 'h'],
        ['Bombeamento de água / esgotamento', 'h'],
        ['Locação de guindaste / grua', 'diária'],
        ['Aluguel de andaime fachadeiro', 'm²'],
        ['Escoramento metálico de laje (locação)', 'm²'],
    ]],
];

// Lista plana: [{ descricao, unidade, categoria }]
export const INSUMOS = CATALOGO.flatMap(([categoria, itens]) =>
    itens.map(([descricao, unidade]) => ({ descricao, unidade, categoria }))
);

const normalizar = (s) => s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/['’]/g, '')
    .replace(/[^a-z0-9\s,./"]/g, ' ');

// Índice pré-normalizado (uma vez por load)
const INDICE = INSUMOS.map(item => ({ item, texto: normalizar(item.descricao) }));

/**
 * Busca insumos: todos os termos digitados precisam aparecer na descrição
 * (sem acento, qualquer ordem). Itens cuja descrição começa pelo 1º termo vêm antes.
 */
export function buscarInsumos(query, limite = 8) {
    const q = normalizar(String(query || '').trim());
    if (q.length < 2) return [];
    const termos = q.split(/\s+/).filter(Boolean);
    if (!termos.length) return [];

    const comeca = [];
    const contem = [];
    for (const { item, texto } of INDICE) {
        if (!termos.every(t => texto.includes(t))) continue;
        (texto.startsWith(termos[0]) ? comeca : contem).push(item);
        if (comeca.length >= limite) break;
    }
    return [...comeca, ...contem].slice(0, limite);
}
